version: "3.8"

services:
  backend:
    build: .
    container_name: backend_express_mysql
    restart: unless-stopped

    ports:
      - "3333:3000"

    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}